name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Install make
        run: apt-get update && apt-get install -y make

      - name: Check format
        run: make check-format

      - name: Run unit tests
        run: make test

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        run: sam build
